### ISSUE TITLE
JoinNode fails

### ISSUE THREAD

**Issue by mfalkiewicz** [mfalkiewicz/st_glm_deconvolution#1]
Following error message pops out after GLM estimation:

```
mfalkiewicz@medusa:~/software/st_glm_deconvolution$ nipype_display_crash crash-20150722-085429-mfalkiewicz-merger.pklz
False False


File: crash-20150722-085429-mfalkiewicz-merger.pklz
Node: eb.merger
Working directory: /home/data/scratch/UP_ST/AF1501/eb/merger


Node inputs:

args = <undefined>
dimension = t
environ = <undefined>
ignore_exception = <undefined>
merged_file = <undefined>
output_type = NIFTI_GZ
terminal_output = <undefined>
tr = <undefined>


Traceback:
Traceback (most recent call last):
  File "/home/mfalkiewicz/software/nipype/nipype/pipeline/plugins/linear.py", line 38, in run
    node.run(updatehash=updatehash)
  File "/home/mfalkiewicz/software/nipype/nipype/pipeline/engine.py", line 1323, in run
    self._get_inputs()
  File "/home/mfalkiewicz/software/nipype/nipype/pipeline/engine.py", line 1519, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/home/mfalkiewicz/software/nipype/nipype/pipeline/engine.py", line 1267, in set_input
    setattr(self.inputs, parameter, deepcopy(val))
  File "/usr/lib/python2.7/dist-packages/traits/trait_handlers.py", line 170, in error
    value )
TraitError: The 'in_filesJ1' trait of a DynamicTraitedSpec instance must be an implementor of, or can be adapted to implement, NoneType or None, but a value of '/home/data/scratch/UP_ST/AF1501/eb/_index_1/glm/beta.nii.gz' <type 'str'> was specified.
Error setting node input:
Node: merger
input: in_filesJ1
results_file: /home/data/scratch/UP_ST/AF1501/eb/_index_1/glm/result_glm.pklz
value: /home/data/scratch/UP_ST/AF1501/eb/_index_1/glm/beta.nii.gz
```

Nipype issue?

**Comment by mfalkiewicz** [comment]
Indeed.
